include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-dynamic: true
    implicit-casts: true
  exclude:
    - '**.g.dart'
    - '**.config.dart'
    - '**.freezed.dart'
    - '**.gr.dart'
    - lib/generated/**

linter:
  rules:
    # Avoid print calls in production code.
    avoid_print: true
    # Use trailing commas for all function calls and declarations.
    require_trailing_commas: true
    # Declare method return types.
    always_declare_return_types: true
    # Prefer using lowerCamelCase for constant names.(LL_CAPS_WITH_UNDERSCORES if false)
    constant_identifier_names: false
    # Prefer declaring const constructors on @immutable classes.
    prefer_const_constructors_in_immutables: true
    # Use key in widget constructors.
    use_key_in_widget_constructors: false
    # Private field could be final.
    prefer_final_fields: true
    # Prefer final in for-each loop variable if reference is not reassigned.
    prefer_final_in_for_each: true
    # Prefer final for variable declarations if they are not reassigned.
    prefer_final_locals: true
    # DO avoid relative imports for files in lib/
    always_use_package_imports: true
    # DO avoid relative imports for files in lib/.
    avoid_relative_lib_imports: true
    # PREFER using const for instantiating constant constructors.
    prefer_const_constructors: true
    # AVOID new keyword to create instances.
    unnecessary_new: true
    # DO await functions that return a Future inside of an async function body.
    unawaited_futures: true
    # DO follow the conventions in the Effective Dart Guide
    # DO place dart: imports before other imports.
    directives_ordering: true
    # DO use single quotes where they wouldn't require additional escapes.
    prefer_single_quotes: true
    # DON'T rename parameters of overridden methods.
    avoid_renaming_method_parameters: false
    # DO use a function declaration to bind a function to a name.
    prefer_function_declarations_over_variables: false
    # DO name source files using lowercase_with_underscores
    file_names: false

errors:
  missing_required_param: error
  missing_return: ignore
  import_of_legacy_library_into_null_safe: error
  annotate_overrides: ignore
  invalid_annotation_target: ignore
  missing_enum_constant_in_switch: error
