name: blog_club
description: Mobile application for iOS/Android
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # HELPERS AND SERVICES
  logger: ^1.1.0
  flutter_secure_storage: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # ARCHITECTURE
  auto_route: ^5.0.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  injectable: ^1.5.3

  # APP ICONS HELPER
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0

  # TESTING
  mocktail: ^0.3.0
  bloc_test: ^9.1.0

  # SERVICES
  injectable_generator: ^1.5.2
  freezed_annotation: ^2.1.0

  # FIREBASE
  firebase_auth: ^3.11.1
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  auto_route_generator: ^5.0.2
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/mock/
    - assets/launcher_icon/

  fonts:
    - family: Isonorm
      fonts:
        - asset: assets/fonts/Isonorm-Regular.otf
          style: normal
          weight: 400
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
        - asset: assets/fonts/RobotoCondensed-BoldItalic.ttf
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          style: normal
          weight: 400
    - family: AppIcons
      fonts:
        - asset: assets/fonts/app_icons.ttf


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/launcher_icon.png"