name: CI for pull requests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        name: Checkout to stable
        with:
          channel: 'stable'
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: Install dependencies
        run: flutter pub get
      - name: Flutter analyze
        run: flutter analyze
      - name: Flutter test
        run: flutter test
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: ./coverage/lcov.info

